#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_fet.py — data-driven generator of a .fet file (example for the fet skill).

    python generate_fet.py data.json mini-school.fet

All the data lives in the JSON file; nothing about a specific school is in the code.
Shows the recommended modelling (see ../../skills/fet/reference.md):
  - days are real DATES ("Mon 14/09"), so one-off exclusions are expressible;
  - a lesson shared by several groups is ONE activity with several <Students>;
  - teacher availability (weekdays, earliest hour, excluded dates) becomes
    ConstraintTeacherNotAvailableTimes at 100%.
Standard library only.
"""
import json
import sys
from datetime import date, timedelta
from xml.sax.saxutils import escape as esc

WD = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def build(cfg):
    d, end = date.fromisoformat(cfg["start"]), date.fromisoformat(cfg["end"])
    holidays = set(cfg.get("holidays", []))
    days = []                                   # (date, label)
    while d <= end:
        if WD[d.weekday()] in cfg["weekdays"] and d.isoformat() not in holidays:
            days.append((d, f"{WD[d.weekday()]} {d:%d/%m}"))
        d += timedelta(days=1)
    hours = cfg["hours"]
    name_of = {dt: lb for dt, lb in days}

    o = ['<?xml version="1.0" encoding="UTF-8"?>', '<fet version="5.47.0">',
         f"<Institution_Name>{esc(cfg['institution'])}</Institution_Name>",
         "<Comments>Generated by generate_fet.py: edit data.json, not this file.</Comments>",
         f"<Days_List><Number_of_Days>{len(days)}</Number_of_Days>"
         + "".join(f"<Day><Name>{lb}</Name></Day>" for _, lb in days) + "</Days_List>",
         f"<Hours_List><Number_of_Hours>{len(hours)}</Number_of_Hours>"
         + "".join(f"<Hour><Name>{h}</Name></Hour>" for h in hours) + "</Hours_List>"]
    subjects = sorted({c["subject"] for c in cfg["courses"]})
    o.append("<Subjects_List>" + "".join(f"<Subject><Name>{esc(s)}</Name></Subject>" for s in subjects)
             + "</Subjects_List>")
    o.append("<Activity_Tags_List></Activity_Tags_List>")
    o.append("<Teachers_List>" + "".join(
        f"<Teacher><Name>{esc(t)}</Name><Comments></Comments></Teacher>" for t in cfg["teachers"])
        + "</Teachers_List>")
    o.append("<Students_List>" + "".join(
        f"<Year><Name>{esc(g)}</Name><Number_of_Students>0</Number_of_Students></Year>"
        for g in cfg["groups"]) + "</Students_List>")

    acts, aid = [], 0
    for c in cfg["courses"]:
        n_blocks = c["hours"] // c["block"]
        first = aid + 1
        for _ in range(n_blocks):
            aid += 1
            acts.append(
                f"<Activity><Teacher>{esc(c['teacher'])}</Teacher><Subject>{esc(c['subject'])}</Subject>"
                + "".join(f"<Students>{esc(g)}</Students>" for g in c["groups"])
                + f"<Duration>{c['block']}</Duration><Total_Duration>{c['hours']}</Total_Duration>"
                f"<Id>{aid}</Id><Activity_Group_Id>{first}</Activity_Group_Id>"
                "<Active>true</Active><Comments></Comments></Activity>")
        c["_ids"] = list(range(first, aid + 1))
    o.append("<Activities_List>" + "".join(acts) + "</Activities_List>")
    o.append("<Buildings_List></Buildings_List>")
    o.append("<Rooms_List><Room><Name>Online</Name><Building></Building><Capacity>30000</Capacity>"
             "<Virtual>false</Virtual><Comments>Online classroom: a normal room with huge capacity</Comments></Room></Rooms_List>")

    tc = ["<ConstraintBasicCompulsoryTime><Weight_Percentage>100</Weight_Percentage>"
          "<Active>true</Active><Comments></Comments></ConstraintBasicCompulsoryTime>"]
    for t, av in cfg["teachers"].items():
        off = []
        first_ok = hours.index(av["not_before"]) if "not_before" in av else 0
        for dt, lb in days:
            whole = (WD[dt.weekday()] not in av.get("days", cfg["weekdays"])
                     or dt.isoformat() in av.get("unavailable_dates", []))
            for i, h in enumerate(hours):
                if whole or i < first_ok:
                    off.append(f"<Not_Available_Time><Day>{lb}</Day><Hour>{h}</Hour></Not_Available_Time>")
        if off:
            tc.append("<ConstraintTeacherNotAvailableTimes><Weight_Percentage>100</Weight_Percentage>"
                      f"<Teacher>{esc(t)}</Teacher><Number_of_Not_Available_Times>{len(off)}"
                      "</Number_of_Not_Available_Times>" + "".join(off)
                      + "<Active>true</Active><Comments></Comments></ConstraintTeacherNotAvailableTimes>")
        tc.append("<ConstraintTeacherMaxHoursDaily><Weight_Percentage>100</Weight_Percentage>"
                  f"<Teacher_Name>{esc(t)}</Teacher_Name>"
                  f"<Maximum_Hours_Daily>{cfg.get('max_hours_daily', len(hours))}</Maximum_Hours_Daily>"
                  "<Active>true</Active><Comments></Comments></ConstraintTeacherMaxHoursDaily>")
    for c in cfg["courses"]:                    # same course: different days (a preference, 95%)
        if len(c["_ids"]) > 1:
            tc.append("<ConstraintMinDaysBetweenActivities><Weight_Percentage>95</Weight_Percentage>"
                      f"<Consecutive_If_Same_Day>true</Consecutive_If_Same_Day>"
                      f"<Number_of_Activities>{len(c['_ids'])}</Number_of_Activities>"
                      + "".join(f"<Activity_Id>{i}</Activity_Id>" for i in c["_ids"])
                      + "<MinDays>1</MinDays><Active>true</Active><Comments></Comments>"
                        "</ConstraintMinDaysBetweenActivities>")
    o.append("<Time_Constraints_List>" + "".join(tc) + "</Time_Constraints_List>")
    o.append("<Space_Constraints_List><ConstraintBasicCompulsorySpace><Weight_Percentage>100"
             "</Weight_Percentage><Active>true</Active><Comments></Comments>"
             "</ConstraintBasicCompulsorySpace></Space_Constraints_List>")
    o.append("</fet>")
    return "\n".join(o) + "\n", len(days), aid


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    with open(sys.argv[1], encoding="utf-8") as fh:
        xml, nd, na = build(json.load(fh))
    with open(sys.argv[2], "w", encoding="utf-8") as fh:
        fh.write(xml)
    print(f"Written {sys.argv[2]}: {nd} days, {na} activities")


if __name__ == "__main__":
    main()
